const modules=[
 {id:'dashboard',label:'Visão geral',group:'Principal',icon:'OV',title:'Visão geral',desc:'Uma visão operacional da empresa em um só lugar.'},
 {id:'commercial',label:'Comercial',group:'Operação',icon:'CO',title:'Comercial',desc:'Clientes, oportunidades, orçamentos, pedidos e vendas.'},
 {id:'purchases',label:'Compras',group:'Operação',icon:'CP',title:'Compras',desc:'Fornecedores, cotações, pedidos de compra e recebimentos.'},
 {id:'stock',label:'Estoque',group:'Operação',icon:'ES',title:'Estoque',desc:'Produtos, saldos, movimentações, reservas e inventário.'},
 {id:'financial',label:'Financeiro',group:'Gestão',icon:'FI',title:'Financeiro',desc:'Contas a pagar, contas a receber, caixa e conciliação.'},
 {id:'fiscal',label:'Fiscal',group:'Gestão',icon:'FC',title:'Fiscal',desc:'NF-e, CT-e, MDF-e, documentos e XMLs simulados.'},
 {id:'logistics',label:'Logística',group:'Operação',icon:'LO',title:'Logística',desc:'Transportes, cargas, viagens, entregas e ocorrências.'},
 {id:'registrations',label:'Cadastros',group:'Base',icon:'CA',title:'Cadastros',desc:'Cadastros mestres que alimentam todos os módulos.'},
 {id:'reports',label:'Relatórios',group:'Gestão',icon:'RE',title:'Relatórios',desc:'Indicadores, análises e relatórios operacionais.'},
 {id:'users',label:'Usuários e permissões',group:'Administração',icon:'US',title:'Usuários e permissões',desc:'Acesso, perfis e permissões por usuário.'},
 {id:'settings',label:'Configurações',group:'Administração',icon:'CO',title:'Configurações',desc:'Preferências, empresa, aparência e parâmetros.'}
];
const demo=[['Pedido #000184','Cliente de Estudo LTDA','R$ 4.850,00','Em andamento'],['NF-e #000183','Empresa Modelo LTDA','R$ 2.340,00','Emitida'],['CT-e #000072','Cliente Logística LTDA','R$ 780,00','Em transporte'],['Compra #000041','Fornecedor Modelo','R$ 6.210,00','Aguardando']];
let current=localStorage.getItem('oculto-route')||'dashboard';
function icon(t){return `<span class="module-icon">${t}</span>`}
function nav(){let groups={};modules.forEach(m=>(groups[m.group]??=[]).push(m));return Object.entries(groups).map(([g,items])=>`<div class="nav-label">${g}</div><div class="nav">${items.map(m=>`<button class="${current===m.id?'active':''}" onclick="route('${m.id}')">${icon(m.icon)}${m.label}</button>`).join('')}</div>`).join('')}
function shell(){return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="mark">O</div><div><strong>OCULTO</strong><span>ERP</span></div></div>${nav()}<div class="side-bottom">Ambiente de produção simulada<br>Fiscal sem transmissão à SEFAZ</div></aside><main class="main"><header class="topbar"><div><div class="eyebrow">OCULTO ERP</div><div class="top-title">${modules.find(m=>m.id===current)?.title||'Visão geral'}</div></div><div class="actions"><button class="theme-btn" onclick="openSettings()">Aparência</button><button class="icon-btn">MV</button></div></header><section class="content">${view()}</section></main></div><nav class="mobile-nav">${[['dashboard','OV','Início'],['commercial','CO','Comercial'],['stock','ES','Estoque'],['financial','FI','Financeiro'],['fiscal','FC','Fiscal']].map(([id,i,l])=>`<button class="${current===id?'active':''}" onclick="route('${id}')"><b>${i}</b>${l}</button>`).join('')}</nav>`}
function view(){if(current==='dashboard')return dashboard();if(current==='settings')return settings();const m=modules.find(x=>x.id===current);return `<div class="hero"><div><div class="eyebrow">MÓDULO</div><h1>${m.title}</h1><p>${m.desc}</p></div><div class="hero-actions"><button class="btn primary">Novo registro</button><button class="btn">Exportar</button></div></div><div class="grid module-grid">${cardsFor(current).map(c=>`<article class="card module-card">${icon(c.i)}<div><h3>${c.t}</h3><p>${c.p}</p></div><button class="btn">Acessar</button></article>`).join('')}</div>`}
function dashboard(){return `<div class="hero"><div><div class="eyebrow">TERÇA-FEIRA · AMBIENTE EMPRESARIAL</div><h1>Bom dia.</h1><p>O centro de operações do OCULTO ERP. Os indicadores abaixo serão alimentados pelos módulos conforme forem implementados.</p></div><div class="hero-actions"><button class="btn orange">+ Nova operação</button></div></div><div class="grid kpis">${[['Receita','R$ 128.450','este mês'],['A receber','R$ 42.780','12 títulos'],['Estoque','R$ 86.210','1.248 itens'],['Pedidos','184','este mês']].map(x=>`<article class="card"><div class="kpi-label">${x[0]}</div><div class="kpi-value">${x[1]}</div><div class="kpi-foot">${x[2]}</div></article>`).join('')}</div><div class="grid dashboard-grid"><article class="card"><div class="card-head"><h2>Atividade recente</h2><span class="muted">Hoje</span></div><div class="list">${demo.map(r=>`<div class="row"><strong>${r[0]}</strong><span>${r[1]}</span><span>${r[2]}</span><span class="badge">${r[3]}</span></div>`).join('')}</div></article><article class="card"><div class="card-head"><h2>Estrutura</h2></div><div class="empty">O dashboard será conectado aos dados reais dos módulos durante a implementação.</div></article></div>`}
function cardsFor(id){const map={commercial:[['CL','Clientes','Base comercial e relacionamento.'],['PD','Pedidos','Pedidos de venda e acompanhamento.'],['OR','Orçamentos','Propostas e oportunidades.']],purchases:[['FO','Fornecedores','Cadastro e relacionamento.'],['CO','Cotações','Cotações e comparativos.'],['PC','Pedidos de compra','Compras e recebimentos.']],stock:[['PR','Produtos','Catálogo e dados fiscais.'],['SA','Saldos','Posição de estoque.'],['MV','Movimentações','Entradas, saídas e ajustes.']],financial:[['CP','Contas a pagar','Obrigações e pagamentos.'],['CR','Contas a receber','Recebimentos e cobranças.'],['CX','Caixa','Fluxo e posição financeira.']],fiscal:[['NF','NF-e','Notas fiscais eletrônicas simuladas.'],['CT','CT-e','Conhecimentos de transporte simulados.'],['MD','MDF-e','Manifestos eletrônicos simulados.']],logistics:[['TR','Transportes','Operações e cargas.'],['VI','Viagens','Planejamento e acompanhamento.'],['EN','Entregas','Status e ocorrências.']],registrations:[['CL','Clientes','Cadastros de clientes.'],['FO','Fornecedores','Cadastros de fornecedores.'],['PR','Produtos','Produtos e serviços.']],reports:[['BI','Indicadores','Visão gerencial.'],['OP','Operacional','Relatórios de operação.'],['FI','Financeiro','Análises financeiras.']],users:[['US','Usuários','Usuários do sistema.'],['PF','Perfis','Perfis de acesso.'],['LG','Auditoria','Histórico de ações.']]};return (map[id]||[]).map(x=>({i:x[0],t:x[1],p:x[2]}))}
function settings(){return `<div class="hero"><div><div class="eyebrow">ADMINISTRAÇÃO</div><h1>Configurações</h1><p>Preferências gerais do OCULTO ERP.</p></div></div><article class="card"><div class="setting"><strong>Aparência</strong><span>Escolha como o OCULTO ERP deve aparecer.</span><div class="theme-options"><button onclick="setTheme('light')">Claro</button><button onclick="setTheme('dark')">Escuro</button><button onclick="setTheme('system')">Sistema</button></div></div><div class="setting"><strong>Empresa</strong><span>Empresa principal e parâmetros operacionais.</span></div><div class="setting"><strong>Ambiente fiscal</strong><span>Simulação educacional. Nenhuma informação é transmitida à SEFAZ.</span></div></article>`}
function openSettings(){route('settings')}
function route(id){current=id;localStorage.setItem('oculto-route',id);render()}
function setTheme(t){localStorage.setItem('oculto-theme',t);applyTheme()}
function applyTheme(){const t=localStorage.getItem('oculto-theme')||'system';document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):t}
function render(){document.getElementById('app').innerHTML=shell();applyTheme()}
window.route=route;window.setTheme=setTheme;window.openSettings=openSettings;applyTheme();render();
