/* OCULTO ERP — Fase 4: Comercial */
(function(){
  const KEYS={customers:'oculto-commercial-customers-v1',products:'oculto-commercial-products-v1',quotes:'oculto-commercial-quotes-v1',orders:'oculto-commercial-orders-v1',finance:'oculto-finance-v1'};
  const read=k=>{try{const x=JSON.parse(localStorage.getItem(k));return Array.isArray(x)?x:[]}catch{return[]}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const uid=p=>p+'-'+String(Date.now()).slice(-7);
  function data(){return{customers:read(KEYS.customers),products:read(KEYS.products),quotes:read(KEYS.quotes),orders:read(KEYS.orders)}}
  function customersView(){const d=data();return `<div class="commercial-page"><div class="module-head"><div><div class="eyebrow">COMERCIAL · CADASTROS</div><h1>Clientes</h1><p>Relacionamento e base comercial da empresa.</p></div><div class="head-actions"><button class="btn ghost" onclick="commercialExport('customers')">Exportar</button><button class="btn primary" onclick="commercialCustomerForm()">+ Novo cliente</button></div></div><div class="commercial-kpis"><article class="card"><span>Total</span><strong>${d.customers.length}</strong><small>clientes cadastrados</small></article><article class="card"><span>Ativos</span><strong>${d.customers.filter(x=>x.active!==false).length}</strong><small>cadastros ativos</small></article><article class="card"><span>Pedidos</span><strong>${d.orders.length}</strong><small>relacionados</small></article></div><article class="card commercial-list"><div class="card-head"><div><span class="section-label">BASE COMERCIAL</span><h2>Clientes</h2></div><input class="commercial-search" placeholder="Pesquisar cliente..." oninput="commercialFilter(this,'customer-row')"></div><div class="commercial-table-head"><span>Cliente</span><span>Documento</span><span>Contato</span><span>Status</span><span></span></div>${d.customers.length?d.customers.map(x=>`<div class="commercial-row customer-row"><span><b>${esc(x.name)}</b><small>${esc(x.email||'')}</small></span><span>${esc(x.document||'—')}</span><span>${esc(x.phone||'—')}</span><em class="status-pill ${x.active===false?'inactive':'active'}">${x.active===false?'Inativo':'Ativo'}</em><button class="row-action" onclick="commercialCustomerForm('${esc(x.id)}')">Editar</button></div>`).join(''):'<div class="empty-state">Nenhum cliente cadastrado.</div>'}</article></div>`}
  function productsView(){const d=data();return `<div class="commercial-page"><div class="module-head"><div><div class="eyebrow">COMERCIAL · CATÁLOGO</div><h1>Produtos e serviços</h1><p>Itens utilizados nas operações comerciais.</p></div><div class="head-actions"><button class="btn primary" onclick="commercialProductForm()">+ Novo produto</button></div></div><article class="card commercial-list"><div class="card-head"><div><span class="section-label">CATÁLOGO</span><h2>Produtos</h2></div><input class="commercial-search" placeholder="Pesquisar produto..." oninput="commercialFilter(this,'product-row')"></div><div class="commercial-table-head"><span>Produto</span><span>SKU</span><span>Categoria</span><span>Preço</span><span></span></div>${d.products.length?d.products.map(x=>`<div class="commercial-row product-row"><span><b>${esc(x.name)}</b><small>${esc(x.unit||'UN')}</small></span><span>${esc(x.sku||'—')}</span><span>${esc(x.category||'—')}</span><strong>${money(x.price)}</strong><button class="row-action" onclick="commercialProductForm('${esc(x.id)}')">Editar</button></div>`).join(''):'<div class="empty-state">Nenhum produto cadastrado.</div>'}</article></div>`}
  function quotesView(){const d=data();return `<div class="commercial-page"><div class="module-head"><div><div class="eyebrow">COMERCIAL · VENDAS</div><h1>Orçamentos</h1><p>Propostas comerciais e aprovação de vendas.</p></div><button class="btn primary" onclick="commercialQuoteForm()">+ Novo orçamento</button></div><article class="card commercial-list"><div class="card-head"><div><span class="section-label">PIPELINE</span><h2>Orçamentos</h2></div></div><div class="commercial-table-head"><span>Número</span><span>Cliente</span><span>Validade</span><span>Total</span><span>Status</span></div>${d.quotes.length?d.quotes.map(x=>`<div class="commercial-row"><span><b>${esc(x.id)}</b><small>${esc(x.created)}</small></span><span>${esc(x.customerName)}</span><span>${esc(x.validUntil||'—')}</span><strong>${money(x.total)}</strong><em class="status-pill ${x.status}">${esc(x.statusLabel||x.status)}</em></div>`).join(''):'<div class="empty-state">Nenhum orçamento criado.</div>'}</article></div>`}
  function ordersView(){const d=data();return `<div class="commercial-page"><div class="module-head"><div><div class="eyebrow">COMERCIAL · PEDIDOS</div><h1>Pedidos de venda</h1><p>Pedidos originados das operações comerciais.</p></div><button class="btn primary" onclick="commercialQuoteForm()">+ Novo pedido</button></div><article class="card commercial-list"><div class="card-head"><div><span class="section-label">PEDIDOS</span><h2>Pedidos de venda</h2></div></div><div class="commercial-table-head"><span>Número</span><span>Cliente</span><span>Total</span><span>Status</span><span></span></div>${d.orders.length?d.orders.map(x=>`<div class="commercial-row"><span><b>${esc(x.id)}</b><small>${esc(x.created)}</small></span><span>${esc(x.customerName)}</span><strong>${money(x.total)}</strong><em class="status-pill ${x.status}">${esc(x.statusLabel||x.status)}</em><button class="row-action" onclick="commercialInvoice('${esc(x.id)}')">Faturar</button></div>`).join(''):'<div class="empty-state">Nenhum pedido criado.</div>'}</article></div>`}
  function customerForm(id){const x=data().customers.find(v=>v.id===id)||{};return modal('Novo cliente',`<form onsubmit="commercialSaveCustomer(event,'${esc(id||'')}')"><label>Nome / razão social<input name="name" value="${esc(x.name)}" required></label><label>CPF / CNPJ<input name="document" value="${esc(x.document)}"></label><div class="form-grid"><label>E-mail<input name="email" type="email" value="${esc(x.email)}"></label><label>Telefone<input name="phone" value="${esc(x.phone)}"></label></div><label>Endereço<input name="address" value="${esc(x.address)}"></label><div class="modal-actions"><button type="button" class="btn ghost" onclick="commercialClose()">Cancelar</button><button class="btn primary">Salvar cliente</button></div></form>`)}
  function productForm(id){const x=data().products.find(v=>v.id===id)||{};return modal('Novo produto',`<form onsubmit="commercialSaveProduct(event,'${esc(id||'')}')"><label>Descrição<input name="name" value="${esc(x.name)}" required></label><div class="form-grid"><label>SKU<input name="sku" value="${esc(x.sku)}"></label><label>Unidade<input name="unit" value="${esc(x.unit||'UN')}"></label></div><div class="form-grid"><label>Categoria<input name="category" value="${esc(x.category)}"></label><label>Preço de venda<input name="price" inputmode="decimal" value="${x.price||''}" required></label></div><div class="modal-actions"><button type="button" class="btn ghost" onclick="commercialClose()">Cancelar</button><button class="btn primary">Salvar produto</button></div></form>`)}
  function quoteForm(){const d=data();return modal('Novo orçamento',`<form onsubmit="commercialSaveQuote(event)"><label>Cliente<select name="customer" required>${d.customers.length?d.customers.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join(''):'<option value="">Cadastre um cliente primeiro</option>'}</select></label><label>Produto<select name="product" required>${d.products.length?d.products.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${money(x.price)}</option>`).join(''):'<option value="">Cadastre um produto primeiro</option>'}</select></label><div class="form-grid"><label>Quantidade<input name="qty" type="number" min="1" value="1" required></label><label>Validade<input name="validUntil" type="date" required></label></div><div class="modal-actions"><button type="button" class="btn ghost" onclick="commercialClose()">Cancelar</button><button class="btn primary">Criar orçamento</button></div></form>`)}
  function modal(title,body){return `<div class="modal-backdrop" id="commercial-modal"><div class="modal"><button class="modal-close" onclick="commercialClose()">×</button><div class="section-label">COMERCIAL</div><h2>${title}</h2>${body}</div></div>`}
  window.commercialCustomerForm=id=>document.body.insertAdjacentHTML('beforeend',customerForm(id));window.commercialProductForm=id=>document.body.insertAdjacentHTML('beforeend',productForm(id));window.commercialQuoteForm=()=>document.body.insertAdjacentHTML('beforeend',quoteForm());window.commercialClose=()=>document.getElementById('commercial-modal')?.remove();
  window.commercialSaveCustomer=e=>{e.preventDefault();const f=new FormData(e.target),d=data(),id=e.target.dataset.id||uid('CLI');const x={id,name:String(f.get('name')).trim(),document:String(f.get('document')).trim(),email:String(f.get('email')).trim(),phone:String(f.get('phone')).trim(),address:String(f.get('address')).trim(),active:true};d.customers.push(x);write(KEYS.customers,d.customers);commercialClose();current='customers';render()};
  window.commercialSaveProduct=e=>{e.preventDefault();const f=new FormData(e.target),d=data(),raw=String(f.get('price')).replace(/\./g,'').replace(',','.');const price=Number(raw);if(!Number.isFinite(price)||price<0)return alert('Informe um preço válido.');d.products.push({id:uid('PRD'),name:String(f.get('name')).trim(),sku:String(f.get('sku')).trim(),unit:String(f.get('unit')).trim(),category:String(f.get('category')).trim(),price});write(KEYS.products,d.products);commercialClose();current='products';render()};
  window.commercialSaveQuote=e=>{e.preventDefault();const f=new FormData(e.target),d=data(),c=d.customers.find(x=>x.id===f.get('customer')),p=d.products.find(x=>x.id===f.get('product'));if(!c||!p)return alert('Cadastre cliente e produto antes do orçamento.');const qty=Number(f.get('qty')),total=qty*p.price;d.quotes.unshift({id:uid('ORC'),customerId:c.id,customerName:c.name,productId:p.id,productName:p.name,qty,total,validUntil:f.get('validUntil'),created:new Date().toISOString().slice(0,10),status:'sent',statusLabel:'Enviado'});write(KEYS.quotes,d.quotes);commercialClose();current='quotes';render()};
  window.commercialInvoice=id=>{const d=data(),o=d.orders.find(x=>x.id===id);if(!o)return;const finance=read(KEYS.finance);if(!finance.some(x=>x.sourceId===id)){finance.unshift({id:uid('FIN'),sourceId:id,type:'receivable',description:'Pedido '+id,party:o.customerName,value:o.total,date:new Date().toISOString().slice(0,10),due:new Date(Date.now()+30*86400000).toISOString().slice(0,10),status:'open'});write(KEYS.finance,finance)}o.status='invoiced';o.statusLabel='Faturado';write(KEYS.orders,d.orders);current='financial';render()};
  window.commercialFilter=(input,cls)=>{const q=input.value.toLowerCase();document.querySelectorAll('.'+cls).forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'grid':'none')};
  window.commercialExport=type=>{const rows=data()[type],csv=Object.keys(rows[0]||{}).join(',')+'\n'+rows.map(x=>Object.values(x).map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='oculto-'+type+'.csv';a.click();URL.revokeObjectURL(u)};
  const originalModuleView=window.moduleView;window.moduleView=m=>{if(m.id==='customers')return customersView();if(m.id==='products')return productsView();if(m.id==='quotes')return quotesView();if(m.id==='orders')return ordersView();return originalModuleView(m)};
})();
