/* OCULTO ERP — Fase 3: Financeiro local-first */
(function(){
  const KEY='oculto-finance-v1';
  const seed=[{id:'FIN-001',type:'receivable',description:'Pedido #000184',party:'Cliente de Estudo LTDA',value:4850,date:'2026-08-05',due:'2026-08-30',status:'open'},{id:'FIN-002',type:'receivable',description:'Pedido #000181',party:'Comercial Modelo',value:7200,date:'2026-08-08',due:'2026-08-28',status:'open'},{id:'FIN-003',type:'payable',description:'Compra #000041',party:'Fornecedor Modelo',value:6210,date:'2026-08-10',due:'2026-08-25',status:'open'},{id:'FIN-004',type:'payable',description:'Serviços operacionais',party:'Serviços Alfa',value:2140,date:'2026-08-12',due:'2026-08-27',status:'open'},{id:'FIN-005',type:'receivable',description:'Pedido #000176',party:'Cliente Logística LTDA',value:3800,date:'2026-08-15',due:'2026-08-20',status:'paid'},{id:'FIN-006',type:'payable',description:'Frete operacional',party:'Transportes Modelo',value:1780,date:'2026-08-17',due:'2026-08-22',status:'paid'}];
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:seed}catch{return seed}}
  function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
  if(!localStorage.getItem(KEY))save(seed);
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  const sum=(a,fn)=>a.reduce((s,x)=>s+(fn(x)?Number(x.value||0):0),0);
  function totals(){const a=load();return{receivable:sum(a,x=>x.type==='receivable'&&x.status==='open'),payable:sum(a,x=>x.type==='payable'&&x.status==='open'),received:sum(a,x=>x.type==='receivable'&&x.status==='paid'),paid:sum(a,x=>x.type==='payable'&&x.status==='paid'),open:a.filter(x=>x.status==='open').length,total:a.length}}
  function chart(){
    const a=load();const months=[...Array(8)].map((_,i)=>{const d=new Date();d.setMonth(d.getMonth()-7+i);return d.toISOString().slice(0,7)});
    const data=months.map(key=>{const m=a.filter(x=>(x.date||'').slice(0,7)===key);return[new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(key+'-15')).replace('.',''),sum(m,x=>x.type==='receivable'),sum(m,x=>x.type==='payable')]});
    const fallback=a.length?null:[['Jan',0,0],['Fev',0,0],['Mar',0,0],['Abr',0,0],['Mai',0,0],['Jun',0,0],['Jul',0,0],['Ago',0,0]];const d=fallback||data,W=720,H=260,p=18,max=Math.max(15000,...d.flatMap(x=>[x[1],x[2]]));const y=v=>H-p-v/max*(H-2*p),pts=i=>d.map((x,n)=>`${p+n*(W-2*p)/(d.length-1)},${y(x[i])}`).join(' '),area=i=>`${pts(i)} ${W-p},${H-p} ${p},${H-p}`;
    return `<div class="ab-chart"><div class="ab-legend"><span><i class="legend-a"></i>Entradas</span><span><i class="legend-b"></i>Saídas</span><b>Comparativo A / B</b></div><div class="ab-plot"><div class="ab-y"><span>${Math.round(max/1000)}k</span><span>${Math.round(max*.66/1000)}k</span><span>${Math.round(max*.33/1000)}k</span><span>0</span></div><div class="ab-svg-wrap"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><g class="ab-grid"><path d="M18 18H702M18 92H702M18 166H702M18 242H702"/></g><polygon points="${area(1)}" class="ab-area-b"/><polygon points="${area(2)}" class="ab-area-a"/><polyline points="${pts(1)}" class="ab-line-b"/><polyline points="${pts(2)}" class="ab-line-a"/>${d.map((x,i)=>{const xx=p+i*(W-2*p)/(d.length-1);return`<circle class="ab-point a" cx="${xx}" cy="${y(x[1])}" r="4" data-month="${x[0]}" data-kind="Entradas" data-value="${x[1]}"/><circle class="ab-point b" cx="${xx}" cy="${y(x[2])}" r="4" data-month="${x[0]}" data-kind="Saídas" data-value="${x[2]}"/>`}).join('')}</svg><div class="ab-tooltip" id="ab-tooltip"><small>Selecione um ponto</small><strong>Dados financeiros</strong></div></div></div><div class="ab-x">${d.map(x=>`<span>${x[0]}</span>`).join('')}</div></div>`;
  }
  function finance(){const a=load(),t=totals();return `<div class="finance-page"><div class="module-head finance-head"><div><div class="eyebrow">GESTÃO · FINANCEIRO</div><h1>Financeiro</h1><p>Controle de contas, recebimentos, pagamentos e fluxo de caixa.</p></div><div class="head-actions"><button class="btn ghost" onclick="financeExport()">Exportar</button><button class="btn primary" onclick="financeForm()">${window.ocultoFinanceIcons?window.ocultoFinanceIcons('plus'):''} Novo lançamento</button></div></div><div class="finance-kpis"><article class="card"><span>Em aberto · Receber</span><strong>${money(t.receivable)}</strong><small>${a.filter(x=>x.type==='receivable'&&x.status==='open').length} títulos em aberto</small></article><article class="card"><span>Em aberto · Pagar</span><strong>${money(t.payable)}</strong><small>${a.filter(x=>x.type==='payable'&&x.status==='open').length} obrigações</small></article><article class="card"><span>Recebido</span><strong>${money(t.received)}</strong><small>movimentação registrada</small></article><article class="card"><span>Pago</span><strong>${money(t.paid)}</strong><small>movimentação registrada</small></article></div><article class="card finance-chart-card"><div class="card-head"><div><span class="section-label">FLUXO DE CAIXA</span><h2>Entradas × saídas</h2></div><span class="select-btn">Últimos 8 meses</span></div>${chart()}</article><article class="card finance-list"><div class="card-head"><div><span class="section-label">LANÇAMENTOS</span><h2>Contas financeiras</h2></div><div class="finance-filters"><button class="filter active" data-fin="all">Todos</button><button class="filter" data-fin="receivable">A receber</button><button class="filter" data-fin="payable">A pagar</button><button class="filter" data-fin="open">Em aberto</button></div></div><div class="finance-table"><div class="finance-table-head"><span>Descrição</span><span>Parceiro</span><span>Vencimento</span><span>Valor</span><span>Status</span><span></span></div>${a.map(x=>`<div class="finance-row" data-type="${x.type}" data-status="${x.status}"><span><b>${x.description}</b><small>${x.id} · ${x.type==='receivable'?'A receber':'A pagar'}</small></span><span>${x.party}</span><span>${new Intl.DateTimeFormat('pt-BR').format(new Date(x.due+'T12:00:00'))}</span><strong>${money(x.value)}</strong><em class="status-pill ${x.status}">${x.status==='open'?'Em aberto':x.type==='receivable'?'Recebido':'Pago'}</em><button class="row-action" onclick="financeToggle('${x.id}')">${x.status==='open'?'Baixar':'Reabrir'}</button></div>`).join('')}</div></article></div>`}
  function form(){return `<div class="modal-backdrop" id="finance-modal"><div class="modal finance-modal"><button class="modal-close" onclick="financeClose()">×</button><div class="section-label">FINANCEIRO</div><h2>Novo lançamento</h2><p>Crie uma conta a pagar ou a receber.</p><form onsubmit="financeSave(event)"><label>Tipo<select name="type"><option value="receivable">A receber</option><option value="payable">A pagar</option></select></label><label>Descrição<input name="description" required placeholder="Ex.: Pedido #000200"></label><label>Cliente / fornecedor<input name="party" required placeholder="Nome da empresa"></label><div class="form-grid"><label>Valor<input name="value" required inputmode="decimal" placeholder="0,00"></label><label>Vencimento<input name="due" type="date" required></label></div><div class="modal-actions"><button type="button" class="btn ghost" onclick="financeClose()">Cancelar</button><button class="btn primary">Salvar lançamento</button></div></form></div></div>`}
  window.financeForm=()=>document.body.insertAdjacentHTML('beforeend',form());window.financeClose=()=>document.getElementById('finance-modal')?.remove();window.financeSave=e=>{e.preventDefault();const f=new FormData(e.target),raw=String(f.get('value')).trim().replace(/\./g,'').replace(',','.');const value=Number(raw);if(!Number.isFinite(value)||value<0)return alert('Informe um valor válido.');const a=load();a.unshift({id:'FIN-'+String(Date.now()).slice(-6),type:f.get('type'),description:String(f.get('description')).trim(),party:String(f.get('party')).trim(),value,date:new Date().toISOString().slice(0,10),due:f.get('due'),status:'open'});save(a);financeClose();current='financial';localStorage.setItem('oculto-route','financial');render()};window.financeToggle=id=>{const a=load(),x=a.find(v=>v.id===id);if(x){x.status=x.status==='open'?'paid':'open';save(a);render()}};window.financeExport=()=>{const a=load(),csv=['id,tipo,descricao,parceiro,valor,vencimento,status',...a.map(x=>[x.id,x.type,x.description,x.party,x.value,x.due,x.status].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),el=document.createElement('a');el.href=u;el.download='oculto-financeiro.csv';el.click();URL.revokeObjectURL(u)};
  window.financeModuleView=finance;window.financeDashboardChart=chart;window.ocultoFinanceIcons=window.ocultoFinanceIcons||((name)=>window.icon?window.icon(name):'');
  const originalModuleView=window.moduleView;window.moduleView=m=>m.id==='financial'?finance():originalModuleView(m);
  const originalRender=window.render;window.render=()=>{originalRender();if(current==='financial'){document.querySelectorAll('.finance-filters .filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.finance-filters .filter').forEach(z=>z.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.finance-row').forEach(r=>{const f=b.dataset.fin;r.style.display=f==='all'||r.dataset.type===f||r.dataset.status===f?'grid':'none'})});document.querySelectorAll('.ab-point').forEach(p=>p.addEventListener('click',()=>{const t=document.getElementById('ab-tooltip');t.innerHTML=`<small>${p.dataset.month} · ${p.dataset.kind}</small><strong>${money(Number(p.dataset.value))}</strong>`;t.classList.add('show')}))}};
})();
