/* OCULTO ERP — Fase 3: Financeiro local-first */
(function(){
  const KEY='oculto-finance-v1';
  const seed=[
    {id:'FIN-001',type:'receivable',description:'Pedido #000184',party:'Cliente de Estudo LTDA',value:4850,date:'2026-08-05',due:'2026-08-30',status:'open'},
    {id:'FIN-002',type:'receivable',description:'Pedido #000181',party:'Comercial Modelo',value:7200,date:'2026-08-08',due:'2026-08-28',status:'open'},
    {id:'FIN-003',type:'payable',description:'Compra #000041',party:'Fornecedor Modelo',value:6210,date:'2026-08-10',due:'2026-08-25',status:'open'},
    {id:'FIN-004',type:'payable',description:'Serviços operacionais',party:'Serviços Alfa',value:2140,date:'2026-08-12',due:'2026-08-27',status:'open'},
    {id:'FIN-005',type:'receivable',description:'Pedido #000176',party:'Cliente Logística LTDA',value:3800,date:'2026-08-15',due:'2026-08-20',status:'paid'},
    {id:'FIN-006',type:'payable',description:'Frete operacional',party:'Transportes Modelo',value:1780,date:'2026-08-17',due:'2026-08-22',status:'paid'}
  ];
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:seed;}catch{return seed;}}
  function save(x){localStorage.setItem(KEY,JSON.stringify(x));}
  if(!localStorage.getItem(KEY)) save(seed);
  function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)}
  function sum(a,fn){return a.reduce((s,x)=>s+(fn(x)?Number(x.value):0),0)}
  function totals(){const a=load();return {receivable:sum(a,x=>x.type==='receivable'&&x.status==='open'),payable:sum(a,x=>x.type==='payable'&&x.status==='open'),received:sum(a,x=>x.type==='receivable'&&x.status==='paid'),paid:sum(a,x=>x.type==='payable'&&x.status==='paid'),open:a.filter(x=>x.status==='open').length}}
  function icon(name){const paths={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',cart:'<circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M3 4h2l2.4 11.2a2 2 0 0 0 2 1.6h7.9a2 2 0 0 0 1.9-1.4L21 8H6"/>',box:'<path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="M4 7.5 12 12l8-4.5M12 12v9"/>',wallet:'<path d="M4 6h15a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14"/><path d="M16 12h5"/>',file:'<path d="M6 2h9l5 5v15H6z"/><path d="M14 2v6h6M9 13h7M9 17h7"/>',truck:'<path d="M3 6h11v11H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',plus:'<path d="M12 5v14M5 12h14"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.file}</svg>`}
  function chart(){
    const data=[['Jan',78,42],['Fev',92,51],['Mar',88,47],['Abr',105,62],['Mai',98,58],['Jun',121,71],['Jul',113,68],['Ago',128,72]];
    const W=720,H=260,p=18,max=150;
    const pts=(idx)=>data.map((d,i)=>`${p+i*(W-2*p)/(data.length-1)},${H-p-(d[idx]*1000/max)*(H-2*p)/1000}`).join(' ');
    const area=(idx)=>{const q=pts(idx).split(' ');return `${q[0]} ${q.join(' ')} ${W-p},${H-p} ${p},${H-p}`};
    return `<div class="ab-chart"><div class="ab-legend"><span><i class="legend-a"></i>Entradas</span><span><i class="legend-b"></i>Saídas</span><b>Comparativo A / B</b></div><div class="ab-plot"><div class="ab-y"><span>150k</span><span>100k</span><span>50k</span><span>0</span></div><div class="ab-svg-wrap"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><g class="ab-grid"><path d="M18 18H702M18 92H702M18 166H702M18 242H702"/></g><polygon points="${area(1)}" class="ab-area-b"/><polygon points="${area(2)}" class="ab-area-a"/><polyline points="${pts(1)}" class="ab-line-b"/><polyline points="${pts(2)}" class="ab-line-a"/>${data.map((d,i)=>{const x=p+i*(W-2*p)/(data.length-1);return `<circle class="ab-point a" cx="${x}" cy="${H-p-(d[1]*1000/max)*(H-2*p)/1000}" r="4" data-month="${d[0]}" data-kind="Entradas" data-value="${d[1]}"/><circle class="ab-point b" cx="${x}" cy="${H-p-(d[2]*1000/max)*(H-2*p)/1000}" r="4" data-month="${d[0]}" data-kind="Saídas" data-value="${d[2]}"/>`}).join('')}</svg><div class="ab-tooltip" id="ab-tooltip"><small>Junho · Entradas</small><strong>R$ 121.000</strong></div></div></div><div class="ab-x">${data.map(d=>`<span>${d[0]}</span>`).join('')}</div></div>`;
  }
  function finance(){
    const a=load(),t=totals();
    return `<div class="finance-page"><div class="module-head finance-head"><div><div class="eyebrow">GESTÃO · FINANCEIRO</div><h1>Financeiro</h1><p>Controle de contas, recebimentos, pagamentos e fluxo de caixa.</p></div><div class="head-actions"><button class="btn ghost" onclick="financeExport()">Exportar</button><button class="btn primary" onclick="financeForm()">${icon('plus')} Novo lançamento</button></div></div>
      <div class="finance-kpis"><article class="card"><span>Em aberto · Receber</span><strong>${money(t.receivable)}</strong><small>${a.filter(x=>x.type==='receivable'&&x.status==='open').length} títulos em aberto</small></article><article class="card"><span>Em aberto · Pagar</span><strong>${money(t.payable)}</strong><small>${a.filter(x=>x.type==='payable'&&x.status==='open').length} obrigações</small></article><article class="card"><span>Recebido</span><strong>${money(t.received)}</strong><small>movimentação registrada</small></article><article class="card"><span>Pago</span><strong>${money(t.paid)}</strong><small>movimentação registrada</small></article></div>
      <article class="card finance-chart-card"><div class="card-head"><div><span class="section-label">FLUXO DE CAIXA</span><h2>Entradas × saídas</h2></div><button class="select-btn">Últimos 8 meses <span>⌄</span></button></div>${chart()}</article>
      <article class="card finance-list"><div class="card-head"><div><span class="section-label">LANÇAMENTOS</span><h2>Contas financeiras</h2></div><div class="finance-filters"><button class="filter active" data-fin="all">Todos</button><button class="filter" data-fin="receivable">A receber</button><button class="filter" data-fin="payable">A pagar</button><button class="filter" data-fin="open">Em aberto</button></div></div><div class="finance-table"><div class="finance-table-head"><span>Descrição</span><span>Parceiro</span><span>Vencimento</span><span>Valor</span><span>Status</span><span></span></div>${a.map(x=>`<div class="finance-row" data-type="${x.type}" data-status="${x.status}"><span><b>${x.description}</b><small>${x.id} · ${x.type==='receivable'?'A receber':'A pagar'}</small></span><span>${x.party}</span><span>${new Intl.DateTimeFormat('pt-BR').format(new Date(x.due+'T12:00:00'))}</span><strong>${money(x.value)}</strong><em class="status-pill ${x.status}">${x.status==='open'?'Em aberto':x.type==='receivable'?'Recebido':'Pago'}</em><button class="row-action" onclick="financeToggle('${x.id}')">${x.status==='open'?'Baixar':'Reabrir'}</button></div>`).join('')}</div></article>
    </div>`;
  }
  function form(){return `<div class="modal-backdrop" id="finance-modal"><div class="modal finance-modal"><button class="modal-close" onclick="financeClose()">×</button><div class="section-label">FINANCEIRO</div><h2>Novo lançamento</h2><p>Crie uma conta a pagar ou a receber.</p><form onsubmit="financeSave(event)"><label>Tipo<select name="type"><option value="receivable">A receber</option><option value="payable">A pagar</option></select></label><label>Descrição<input name="description" required placeholder="Ex.: Pedido #000200"></label><label>Cliente / fornecedor<input name="party" required placeholder="Nome da empresa"></label><div class="form-grid"><label>Valor<input name="value" required inputmode="decimal" placeholder="0,00"></label><label>Vencimento<input name="due" type="date" required></label></div><div class="modal-actions"><button type="button" class="btn ghost" onclick="financeClose()">Cancelar</button><button class="btn primary">Salvar lançamento</button></div></form></div></div>`}
  window.financeForm=function(){document.body.insertAdjacentHTML('beforeend',form())};window.financeClose=function(){document.getElementById('finance-modal')?.remove()};window.financeSave=function(e){e.preventDefault();const f=new FormData(e.target);const a=load();a.unshift({id:'FIN-'+String(Date.now()).slice(-6),type:f.get('type'),description:f.get('description'),party:f.get('party'),value:Number(String(f.get('value')).replace('.','').replace(',','.'))||0,date:new Date().toISOString().slice(0,10),due:f.get('due'),status:'open'});save(a);financeClose();current='financial';localStorage.setItem('oculto-route','financial');render();};
  window.financeToggle=function(id){const a=load(),x=a.find(v=>v.id===id);if(x){x.status=x.status==='open'?'paid':'open';save(a);render();}};
  window.financeExport=function(){const a=load();const csv=['id,tipo,descricao,parceiro,valor,vencimento,status',...a.map(x=>[x.id,x.type,x.description,x.party,x.value,x.due,x.status].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const el=document.createElement('a');el.href=u;el.download='oculto-financeiro.csv';el.click();URL.revokeObjectURL(u)};
  window.financeModuleView=finance;
  window.financeDashboardChart=chart;
  window.ocultoFinanceIcons=icon;
  const originalDashboard=window.dashboard;const originalModuleView=window.moduleView;
  window.dashboard=function(){let html=originalDashboard();const tt=totals();html=html.replace(/<div class="chart">[\s\S]*?<\/div><div class="chart-x">[\s\S]*?<\/div>/,chart());html=html.replace('R$ 128.450','R$ '+(tt.receivable+tt.received).toLocaleString('pt-BR',{minimumFractionDigits:0}));return html};
  window.moduleView=function(m){return m.id==='financial'?finance():originalModuleView(m)};
  const oldRender=window.render;window.render=function(){oldRender();if(current==='financial'){document.querySelectorAll('.finance-filters .filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.finance-filters .filter').forEach(z=>z.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.finance-row').forEach(r=>{const f=b.dataset.fin;r.style.display=f==='all'||r.dataset.type===f||r.dataset.status===f?'grid':'none'})});document.querySelectorAll('.ab-point').forEach(p=>p.addEventListener('click',()=>{const t=document.getElementById('ab-tooltip');t.innerHTML=`<small>${p.dataset.month} · ${p.dataset.kind}</small><strong>R$ ${Number(p.dataset.value*1000).toLocaleString('pt-BR')}</strong>`;t.classList.add('show')}));}}
})();
