(function(){
  const originalSetView=window.setView;
  const app=document.getElementById('app');
  function card(title,count,action){return `<div class="card"><div class="card-head"><div class="card-title">${title}</div><span class="muted">${count}</span></div><div class="form-actions"><button class="primary" onclick="${action}">Abrir</button></div></div>`}
  function cadastros(){const d=LabStore.load();return `<div class="page-head"><div><div class="eyebrow">Base de estudo</div><h1>Cadastros</h1><div class="muted">Dados reutilizáveis para criar cenários fiscais.</div></div><button class="secondary" onclick="LabStore.export();toast('Ambiente exportado.')">Exportar ambiente</button></div><div class="grid">${card('Empresas',d.companies.length,"alert('Cadastro de empresas disponível para a próxima etapa.')")}${card('Clientes',d.customers.length,"alert('Cadastro de clientes disponível para a próxima etapa.')")}${card('Produtos',d.products.length,"alert('Cadastro de produtos disponível para a próxima etapa.')")}${card('Transportadoras',d.carriers.length,"alert('Cadastro de transportadoras disponível para a próxima etapa.')")}${card('Veículos',d.vehicles.length,"alert('Cadastro de veículos disponível para a próxima etapa.')")}${card('Motoristas',d.drivers.length,"alert('Cadastro de motoristas disponível para a próxima etapa.')")}</div><div class="card"><div class="card-title">Ambiente de demonstração</div><p class="muted">O laboratório já possui dados de exemplo para acelerar os testes. Você pode exportar o ambiente e restaurá-lo posteriormente.</p><div class="form-actions"><button class="secondary" onclick="LabStore.reset();toast('Dados de demonstração restaurados.');setView('cadastros')">Restaurar demonstração</button><label class="secondary" style="display:inline-flex;align-items:center;cursor:pointer">Importar ambiente<input type="file" accept="application/json" style="display:none" onchange="LabStore.import(this.files[0]).then(()=>{toast('Ambiente importado.');setView('cadastros')}).catch(()=>toast('Arquivo inválido.'))"></label></div></div>`}
  function xmlPreview(){const id=prompt('Informe o ID do documento para visualizar o XML simulado:');if(!id)return;const d=JSON.parse(localStorage.getItem('fiscal-documents')||'[]').find(x=>x.id===id);if(!d){toast('Documento não encontrado.');return}const xml=XmlEngine.generate(d);app.innerHTML=`<div class="document-toolbar"><div><div class="eyebrow">Laboratório fiscal</div><h1>XML simulado</h1><div class="muted">Sem assinatura digital e sem transmissão.</div></div><button class="secondary" onclick="setView('documents')">Voltar</button></div><div class="card"><pre style="white-space:pre-wrap;overflow:auto;background:#141311;color:#eeeae2;padding:24px;border-radius:14px;line-height:1.6">${esc(xml)}</pre><div class="form-actions"><button class="primary" onclick="navigator.clipboard.writeText(${JSON.stringify(xml)});toast('XML copiado.')">Copiar XML</button></div></div>`}
  window.setView=function(view){if(view==='cadastros'){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));app.innerHTML=cadastros();window.scrollTo(0,0);return}if(originalSetView)originalSetView(view)};
  window.openXmlPreview=xmlPreview;
})();
