(function(){
  const originalSetView=window.setView;
  const app=document.getElementById('app');
  const docs=()=>JSON.parse(localStorage.getItem('fiscal-documents')||'[]');
  const saveDocs=d=>localStorage.setItem('fiscal-documents',JSON.stringify(d));
  function card(title,count,action){return `<div class="card"><div class="card-head"><div class="card-title">${title}</div><span class="muted">${count}</span></div><div class="form-actions"><button class="primary" onclick="${action}">Abrir</button></div></div>`}
  function cadastros(){const d=LabStore.load();return `<div class="page-head"><div><div class="eyebrow">Base de estudo</div><h1>Cadastros</h1><div class="muted">Dados reutilizáveis para criar cenários fiscais.</div></div><button class="secondary" onclick="LabStore.export();toast('Ambiente exportado.')">Exportar ambiente</button></div><div class="grid">${card('Empresas',d.companies.length,"alert('Cadastro de empresas disponível para a próxima etapa.')")}${card('Clientes',d.customers.length,"alert('Cadastro de clientes disponível para a próxima etapa.')")}${card('Produtos',d.products.length,"alert('Cadastro de produtos disponível para a próxima etapa.')")}${card('Transportadoras',d.carriers.length,"alert('Cadastro de transportadoras disponível para a próxima etapa.')")}${card('Veículos',d.vehicles.length,"alert('Cadastro de veículos disponível para a próxima etapa.')")}${card('Motoristas',d.drivers.length,"alert('Cadastro de motoristas disponível para a próxima etapa.')")}</div><div class="card"><div class="card-title">Ambiente de demonstração</div><p class="muted">Dados de exemplo já carregados para testar os fluxos sem começar do zero.</p><div class="form-actions"><button class="secondary" onclick="LabStore.reset();toast('Dados de demonstração restaurados.');setView('cadastros')">Restaurar demonstração</button><label class="secondary" style="display:inline-flex;align-items:center;cursor:pointer">Importar ambiente<input type="file" accept="application/json" style="display:none" onchange="LabStore.import(this.files[0]).then(()=>{toast('Ambiente importado.');setView('cadastros')}).catch(()=>toast('Arquivo inválido.'))"></label></div></div>`}
  function scenario(){const now=new Date().toISOString().slice(0,10).split('-').reverse().join('/');const base={date:now,series:'1',issuer:'Empresa de Estudo LTDA',cnpj:'00.000.000/0001-00'};const nf={...base,id:'NFE-DEMO-000001',type:'NFE',number:'000001',recipient:'Cliente de Estudo LTDA',recipientDoc:'11.111.111/0001-11',product:'Mercadoria para estudo',qty:'2',unit:'150',ncm:'0000.00.00',cfop:'5102',key:FiscalEngine.key({uf:'RJ',cnpj:'00000000000191',model:'55',series:'001',number:'000000001'})};const ct={...base,id:'CTE-DEMO-000001',type:'CTE',number:'000001',issuer:'Transportes de Estudo LTDA',sender:'Indústria de Estudo LTDA',receiver:'Cliente de Estudo LTDA',origin:'Rio de Janeiro/RJ',destination:'São Paulo/SP',freight:'450',cargo:'300',weight:'120',relatedNfeId:nf.id};const md={...base,id:'MDFE-DEMO-000001',type:'MDFE',number:'000001',issuer:'Transportes de Estudo LTDA',vehicle:'ABC1D23',driver:'Motorista de Estudo',origin:'RJ',destination:'SP',documents:'NF-e 000001 / CT-e 000001',weight:'120',value:'300',relatedNfeId:nf.id,relatedCteId:ct.id};const all=docs().filter(d=>!String(d.id).startsWith('NFE-DEMO-')&&!String(d.id).startsWith('CTE-DEMO-')&&!String(d.id).startsWith('MDFE-DEMO-'));saveDocs([...all,nf,ct,md]);toast('Cenário completo criado.');setView('documents')}
  function xmlPreview(){const id=prompt('Informe o ID do documento para visualizar o XML simulado:');if(!id)return;const d=docs().find(x=>x.id===id);if(!d){toast('Documento não encontrado.');return}const xml=XmlEngine.generate(d);app.innerHTML=`<div class="document-toolbar"><div><div class="eyebrow">Laboratório fiscal</div><h1>XML simulado</h1><div class="muted">Sem assinatura digital e sem transmissão.</div></div><button class="secondary" onclick="setView('documents')">Voltar</button></div><div class="card"><pre style="white-space:pre-wrap;overflow:auto;background:#141311;color:#eeeae2;padding:24px;border-radius:14px;line-height:1.6">${esc(xml)}</pre><div class="form-actions"><button class="primary" onclick="navigator.clipboard.writeText(${JSON.stringify(xml)});toast('XML copiado.')">Copiar XML</button></div></div>`}
  function inject(){if(!window.state)return;const head=document.querySelector('.page-head');if(!head)return;if(state.view==='dashboard'&&!document.querySelector('.lab-actions')){const card=document.querySelector('.quick-grid')?.parentElement?.parentElement;if(card){const box=document.createElement('div');box.className='card lab-actions';box.innerHTML='<div class="card-head"><div class="card-title">Laboratório</div><span class="muted">Teste rápido</span></div><p class="muted">Crie NF-e, CT-e e MDF-e relacionados em um único cenário.</p><div class="form-actions"><button class="primary" onclick="createStudyScenario()">Criar cenário completo</button></div>';card.parentNode.insertBefore(box,card.nextSibling)}}if(state.view==='documents'&&!document.querySelector('.xml-access')){const b=document.createElement('button');b.className='secondary xml-access';b.textContent='XML simulado';b.onclick=xmlPreview;head.appendChild(b)}}
  window.createStudyScenario=scenario;
  window.setView=function(view){if(view==='cadastros'){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));app.innerHTML=cadastros();window.scrollTo(0,0);return}if(originalSetView)originalSetView(view);setTimeout(inject,0)};
  window.openXmlPreview=xmlPreview;
  new MutationObserver(()=>setTimeout(inject,0)).observe(app,{childList:true,subtree:true});
  setTimeout(inject,100);
})();
