/* OCULTO ERP — Fase 4 final: Comercial + correções mobile/light */
(function(){
  const K={customers:'oculto-commercial-customers-v1',products:'oculto-commercial-products-v1',quotes:'oculto-commercial-quotes-v1',orders:'oculto-commercial-orders-v1',finance:'oculto-finance-v1'};
  const read=k=>{try{const v=JSON.parse(localStorage.getItem(k));return Array.isArray(v)?v:[]}catch{return[]}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const uid=p=>p+'-'+String(Date.now()).slice(-7);
  const data=()=>({customers:read(K.customers),products:read(K.products),quotes:read(K.quotes),orders:read(K.orders)});
  let tab='overview';
  const iconMap={dashboard:'dashboard',commercial:'commercial',stock:'stock',financial:'financial',fiscal:'fiscal'};
  function icon(name){return window.ocultoIcon?window.ocultoIcon(name):`<span class="module-icon">${esc(name)}</span>`}
  function modal(title,body){return `<div class="modal-backdrop" id="phase4-modal"><div class="modal"><button class="modal-close" onclick="phase4Close()">×</button><div class="section-label">COMERCIAL</div><h2>${title}</h2>${body}</div></div>`}
  function k(label,value,detail){return `<article class="card phase4-kpi"><span>${label}</span><strong>${value}</strong><small>${detail}</small></article>`}
  function shell(head,body){return `<div class="commercial-page phase4-page"><div class="module-head"><div><div class="eyebrow">COMERCIAL · OPERAÇÃO</div><h1>${head}</h1><p>Clientes, produtos, propostas e pedidos em um único fluxo comercial.</p></div><div class="head-actions"><button class="btn ghost" onclick="phase4Export()">Exportar</button><button class="btn primary" onclick="phase4New()">${icon('plus')} Nova operação</button></div></div><nav class="phase4-tabs" aria-label="Comercial"><button class="${tab==='overview'?'active':''}" onclick="phase4Tab('overview')">Visão geral</button><button class="${tab==='customers'?'active':''}" onclick="phase4Tab('customers')">Clientes</button><button class="${tab==='products'?'active':''}" onclick="phase4Tab('products')">Produtos</button><button class="${tab==='quotes'?'active':''}" onclick="phase4Tab('quotes')">Orçamentos</button><button class="${tab==='orders'?'active':''}" onclick="phase4Tab('orders')">Pedidos</button></nav>${body}</div>`}
  function overview(){const d=data(),approved=d.quotes.filter(x=>x.status==='approved').length,open=d.orders.filter(x=>x.status!=='invoiced').length;return shell('Comercial',`<div class="phase4-kpis">${k('Clientes',d.customers.length,'cadastros comerciais')}${k('Produtos',d.products.length,'itens no catálogo')}${k('Orçamentos',d.quotes.length,'propostas registradas')}${k('Pedidos',d.orders.length,'pedidos de venda')}</div><div class="phase4-overview-grid"><article class="card phase4-flow"><div class="card-head"><div><span class="section-label">FLUXO COMERCIAL</span><h2>Do contato ao recebimento</h2></div></div><div class="flow-steps"><div><b>01</b><strong>Cliente</strong><small>Cadastro comercial</small></div><i>→</i><div><b>02</b><strong>Orçamento</strong><small>Proposta e validade</small></div><i>→</i><div><b>03</b><strong>Pedido</strong><small>Venda aprovada</small></div><i>→</i><div><b>04</b><strong>Financeiro</strong><small>Conta a receber</small></div></div></article><article class="card phase4-status"><div class="card-head"><div><span class="section-label">PIPELINE</span><h2>Status</h2></div></div><div class="phase4-stat-row"><span>Orçamentos aprovados</span><strong>${approved}</strong></div><div class="phase4-stat-row"><span>Pedidos em aberto</span><strong>${open}</strong></div><div class="phase4-stat-row"><span>Pedidos faturados</span><strong>${d.orders.filter(x=>x.status==='invoiced').length}</strong></div></article></div><article class="card commercial-list"><div class="card-head"><div><span class="section-label">ÚLTIMAS OPERAÇÕES</span><h2>Pedidos de venda</h2></div><button class="link-btn" onclick="phase4Tab('orders')">Ver todos →</button></div>${orderRows(d.orders.slice(0,5))}</article>`)}
  function orderRows(rows){return rows.length?`<div class="commercial-table-head"><span>Pedido</span><span>Cliente</span><span>Data</span><span>Total</span><span>Status</span></div>${rows.map(o=>`<div class="commercial-row"><span><b>${esc(o.id)}</b><small>${esc(o.created||'')}</small></span><span>${esc(o.customerName)}</span><span>${esc(o.created||'—')}</span><strong>${money(o.total)}</strong><em class="status-pill ${esc(o.status||'open')}">${esc(o.statusLabel||'Em aberto')}</em></div>`).join('')}`:'<div class="empty-state">Nenhum pedido de venda registrado.</div>'}
  function customers(){const d=data();return shell('Clientes',`<article class="card commercial-list"><div class="card-head"><div><span class="section-label">BASE COMERCIAL</span><h2>Clientes</h2></div><button class="btn primary" onclick="phase4Customer()">+ Novo cliente</button></div><div class="commercial-table-head"><span>Cliente</span><span>Documento</span><span>Contato</span><span>Status</span><span></span></div>${d.customers.length?d.customers.map(x=>`<div class="commercial-row phase4-filter-row"><span><b>${esc(x.name)}</b><small>${esc(x.email||'')}</small></span><span>${esc(x.document||'—')}</span><span>${esc(x.phone||'—')}</span><em class="status-pill active">Ativo</em><button class="row-action" onclick="phase4Customer('${esc(x.id)}')">Editar</button></div>`).join(''):'<div class="empty-state">Nenhum cliente cadastrado.</div>'}</article>`)}
  function products(){const d=data();return shell('Produtos e serviços',`<article class="card commercial-list"><div class="card-head"><div><span class="section-label">CATÁLOGO</span><h2>Produtos</h2></div><button class="btn primary" onclick="phase4Product()">+ Novo produto</button></div><div class="commercial-table-head"><span>Produto</span><span>SKU</span><span>Categoria</span><span>Preço</span><span></span></div>${d.products.length?d.products.map(x=>`<div class="commercial-row phase4-filter-row"><span><b>${esc(x.name)}</b><small>${esc(x.unit||'UN')}</small></span><span>${esc(x.sku||'—')}</span><span>${esc(x.category||'—')}</span><strong>${money(x.price)}</strong><button class="row-action" onclick="phase4Product('${esc(x.id)}')">Editar</button></div>`).join(''):'<div class="empty-state">Nenhum produto cadastrado.</div>'}</article>`)}
  function quotes(){const d=data();return shell('Orçamentos',`<article class="card commercial-list"><div class="card-head"><div><span class="section-label">PIPELINE DE VENDAS</span><h2>Orçamentos</h2></div><button class="btn primary" onclick="phase4Quote()">+ Novo orçamento</button></div><div class="commercial-table-head"><span>Orçamento</span><span>Cliente</span><span>Validade</span><span>Total</span><span>Status</span></div>${d.quotes.length?d.quotes.map(x=>`<div class="commercial-row"><span><b>${esc(x.id)}</b><small>${esc(x.created||'')}</small></span><span>${esc(x.customerName)}</span><span>${esc(x.validUntil||'—')}</span><strong>${money(x.total)}</strong><span class="phase4-row-actions"><em class="status-pill ${esc(x.status)}">${esc(x.statusLabel||'Enviado')}</em>${x.status!=='approved'?`<button class="row-action" onclick="phase4Approve('${esc(x.id)}')">Aprovar</button>`:''}</span></div>`).join(''):'<div class="empty-state">Nenhum orçamento criado.</div>'}</article>`)}
  function orders(){const d=data();return shell('Pedidos de venda',`<article class="card commercial-list"><div class="card-head"><div><span class="section-label">VENDAS</span><h2>Pedidos</h2></div></div>${orderRows(d.orders.map(o=>({...o})).reverse()).replaceAll('class="commercial-table-head"','class="commercial-table-head phase4-order-head"')}</article>`)}
  function customerForm(id){const x=data().customers.find(v=>v.id===id)||{};return modal(id?'Editar cliente':'Novo cliente',`<form onsubmit="phase4SaveCustomer(event,'${esc(id||'')}')"><label>Nome / razão social<input name="name" value="${esc(x.name)}" required></label><div class="form-grid"><label>CPF / CNPJ<input name="document" value="${esc(x.document)}"></label><label>Telefone<input name="phone" value="${esc(x.phone)}"></label></div><label>E-mail<input name="email" type="email" value="${esc(x.email)}"></label><label>Endereço<input name="address" value="${esc(x.address)}"></label><div class="modal-actions"><button type="button" class="btn ghost" onclick="phase4Close()">Cancelar</button><button class="btn primary">Salvar cliente</button></div></form>`)}
  function productForm(id){const x=data().products.find(v=>v.id===id)||{};return modal(id?'Editar produto':'Novo produto',`<form onsubmit="phase4SaveProduct(event,'${esc(id||'')}')"><label>Descrição<input name="name" value="${esc(x.name)}" required></label><div class="form-grid"><label>SKU<input name="sku" value="${esc(x.sku)}"></label><label>Unidade<input name="unit" value="${esc(x.unit||'UN')}"></label></div><div class="form-grid"><label>Categoria<input name="category" value="${esc(x.category)}"></label><label>Preço de venda<input name="price" inputmode="decimal" value="${x.price||''}" required></label></div><div class="modal-actions"><button type="button" class="btn ghost" onclick="phase4Close()">Cancelar</button><button class="btn primary">Salvar produto</button></div></form>`)}
  function quoteForm(){const d=data();return modal('Novo orçamento',`<form onsubmit="phase4SaveQuote(event)"><label>Cliente<select name="customer" required>${d.customers.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')||'<option value="">Cadastre um cliente</option>'}</select></label><label>Produto<select name="product" required>${d.products.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${money(x.price)}</option>`).join('')||'<option value="">Cadastre um produto</option>'}</select></label><div class="form-grid"><label>Quantidade<input name="qty" type="number" min="1" value="1" required></label><label>Validade<input name="validUntil" type="date" required></label></div><div class="modal-actions"><button type="button" class="btn ghost" onclick="phase4Close()">Cancelar</button><button class="btn primary">Criar orçamento</button></div></form>`)}
  window.phase4Tab=t=>{tab=t;render()};window.phase4Close=()=>document.getElementById('phase4-modal')?.remove();window.phase4Customer=id=>document.body.insertAdjacentHTML('beforeend',customerForm(id));window.phase4Product=id=>document.body.insertAdjacentHTML('beforeend',productForm(id));window.phase4Quote=()=>document.body.insertAdjacentHTML('beforeend',quoteForm());window.phase4New=()=>tab==='customers'?phase4Customer():tab==='products'?phase4Product():phase4Quote();
  window.phase4SaveCustomer=(e,id)=>{e.preventDefault();const f=new FormData(e.target),a=data().customers,x={id:id||uid('CLI'),name:String(f.get('name')).trim(),document:String(f.get('document')).trim(),email:String(f.get('email')).trim(),phone:String(f.get('phone')).trim(),address:String(f.get('address')).trim(),active:true};const i=a.findIndex(v=>v.id===id);i>=0?a[i]=x:a.unshift(x);write(K.customers,a);phase4Close();tab='customers';render()};
  window.phase4SaveProduct=(e,id)=>{e.preventDefault();const f=new FormData(e.target),a=data().products,raw=String(f.get('price')).replace(/\./g,'').replace(',','.'),price=Number(raw);if(!Number.isFinite(price)||price<0)return alert('Informe um preço válido.');const x={id:id||uid('PRD'),name:String(f.get('name')).trim(),sku:String(f.get('sku')).trim(),unit:String(f.get('unit')).trim()||'UN',category:String(f.get('category')).trim(),price},i=a.findIndex(v=>v.id===id);i>=0?a[i]=x:a.unshift(x);write(K.products,a);phase4Close();tab='products';render()};
  window.phase4SaveQuote=e=>{e.preventDefault();const f=new FormData(e.target),d=data(),c=d.customers.find(x=>x.id===f.get('customer')),p=d.products.find(x=>x.id===f.get('product')),qty=Number(f.get('qty'));if(!c||!p||qty<1)return alert('Cadastre cliente e produto antes do orçamento.');d.quotes.unshift({id:uid('ORC'),customerId:c.id,customerName:c.name,productId:p.id,productName:p.name,qty,total:qty*p.price,validUntil:f.get('validUntil'),created:new Date().toISOString().slice(0,10),status:'sent',statusLabel:'Enviado'});write(K.quotes,d.quotes);phase4Close();tab='quotes';render()};
  window.phase4Approve=id=>{const d=data(),q=d.quotes.find(x=>x.id===id);if(!q)return;q.status='approved';q.statusLabel='Aprovado';const order={id:uid('PED'),quoteId:q.id,customerName:q.customerName,total:q.total,created:new Date().toISOString().slice(0,10),status:'open',statusLabel:'Em aberto'};d.orders.unshift(order);write(K.quotes,d.quotes);write(K.orders,d.orders);tab='orders';render()};
  window.phase4Export=()=>{const d=data(),rows=[['tipo','id','cliente','valor','data','status'],...d.orders.map(x=>['pedido',x.id,x.customerName,x.total,x.created,x.status]),...d.quotes.map(x=>['orcamento',x.id,x.customerName,x.total,x.created,x.status])],csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='oculto-comercial.csv';a.click();URL.revokeObjectURL(u)};
  const previous=window.moduleView;window.moduleView=function(m){if(m.id!=='commercial')return previous(m);return tab==='customers'?customers():tab==='products'?products():tab==='quotes'?quotes():tab==='orders'?orders():overview()};
  const oldRender=window.render;window.render=function(){oldRender();document.querySelectorAll('.module-icon').forEach(el=>{if(!el.querySelector('svg')&&el.textContent.trim())el.outerHTML=icon(el.textContent.trim())});document.querySelectorAll('.mobile-nav button b').forEach(b=>{if(!b.querySelector('svg'))b.outerHTML=icon(b.textContent.trim())})};
})();
