/* Educational XML generator. Deliberately not an official fiscal XML and never transmitted. */
(function(){
  const esc=v=>String(v??'').replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','\"':'&quot;'}[c]));
  const normalize=t=>String(t||'').toUpperCase().replace(/-/g,'');
  function generate(doc){
    const type=normalize(doc.type), tag=type==='NFE'?'NFe':type==='CTE'?'CTe':'MDFe';
    const lines=(doc.productLines||[]).map((p,i)=>`    <Item numero="${i+1}"><Codigo>${esc(p.code)}</Codigo><Descricao>${esc(p.description)}</Descricao><NCM>${esc(p.ncm)}</NCM><CFOP>${esc(p.cfop)}</CFOP><Unidade>${esc(p.unit||'UN')}</Unidade><Quantidade>${esc(p.qty)}</Quantidade><ValorUnitario>${Number(p.unitPrice||0).toFixed(2)}</ValorUnitario><ValorTotal>${Number(p.total||0).toFixed(2)}</ValorTotal></Item>`).join('\n');
    const related=[doc.relatedNfeId,doc.relatedCteId].filter(Boolean).map(id=>`    <DocumentoRelacionadoId>${esc(id)}</DocumentoRelacionadoId>`).join('\n');
    return `<?xml version="1.0" encoding="UTF-8"?>\n<DocumentoSimulado xmlns="urn:fiscal-generator:estudo" tipo="${tag}" modelo="${esc(doc.model)}" validadeFiscal="false">\n  <Identificacao><Numero>${esc(doc.number)}</Numero><Serie>${esc(doc.series)}</Serie><Chave>${esc(doc.key)}</Chave><Ambiente>SIMULACAO_EDUCACIONAL</Ambiente></Identificacao>\n  <Emitente><RazaoSocial>${esc(doc.issuer)}</RazaoSocial><CNPJ>${esc(doc.cnpj)}</CNPJ><UF>${esc(doc.uf)}</UF></Emitente>\n  ${doc.recipient?`<Destinatario><RazaoSocial>${esc(doc.recipient)}</RazaoSocial><Documento>${esc(doc.recipientDoc||'')}</Documento></Destinatario>`:''}\n  ${type==='CTE'?`<Prestacao><Remetente>${esc(doc.sender||'')}</Remetente><Recebedor>${esc(doc.receiver||'')}</Recebedor><Origem>${esc(doc.origin||'')}</Origem><Destino>${esc(doc.destination||'')}</Destino><ValorCarga>${Number(doc.cargo||0).toFixed(2)}</ValorCarga><Frete>${Number(doc.freight||0).toFixed(2)}</Frete><Peso>${Number(doc.weight||0).toFixed(2)}</Peso></Prestacao>`:''}\n  ${type==='MDFE'?`<Manifesto><Veiculo>${esc(doc.vehicle||'')}</Veiculo><Motorista>${esc(doc.driver||'')}</Motorista><Origem>${esc(doc.origin||'')}</Origem><Destino>${esc(doc.destination||'')}</Destino><Percurso>${esc(doc.route||'')}</Percurso><Peso>${Number(doc.weight||0).toFixed(2)}</Peso><ValorCarga>${Number(doc.value||0).toFixed(2)}</ValorCarga></Manifesto>`:''}\n  ${type==='NFE'?`<Itens>\n${lines}\n  </Itens><Totais><Produtos>${Number(doc.totalProducts||0).toFixed(2)}</Produtos></Totais>`:''}\n  <Relacionamentos>\n${related}\n  </Relacionamentos>\n  <Aviso>DOCUMENTO SIMULADO — SEM VALIDADE FISCAL — NAO TRANSMITIDO A SEFAZ</Aviso>\n</DocumentoSimulado>`;
  }
  window.XmlEngine={generate};
})();
