window.XmlEngine={
  esc(v=''){return String(v).replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','\"':'&quot;'}[c]))},
  generate(doc){
    const e=this.esc.bind(this), type=doc.type==='NFE'?'NFe':doc.type==='CTE'?'CTe':'MDFe', model=doc.type==='NFE'?'55':doc.type==='CTE'?'57':'58';
    const lines=(doc.productLines||[]).map(p=>`    <Item><Codigo>${e(p.code)}</Codigo><Descricao>${e(p.description)}</Descricao><NCM>${e(p.ncm)}</NCM><CFOP>${e(p.cfop)}</CFOP><Quantidade>${e(p.qty)}</Quantidade><ValorUnitario>${e(Number(p.unitPrice||0).toFixed(2))}</ValorUnitario><ValorTotal>${e(Number(p.total||0).toFixed(2))}</ValorTotal></Item>`).join('\n');
    let body=`  <Emitente><RazaoSocial>${e(doc.issuer)}</RazaoSocial><CNPJ>${e(doc.cnpj)}</CNPJ><UF>${e(doc.uf||'')}</UF></Emitente>\n`;
    if(type==='NFe')body+=`  <Destinatario><RazaoSocial>${e(doc.recipient)}</RazaoSocial><Documento>${e(doc.recipientDoc||'')}</Documento></Destinatario>\n  <Itens>${lines}</Itens>\n  <Totais><ValorProdutos>${e(Number(doc.totalProducts||Number(doc.qty||0)*Number(doc.unit||0)).toFixed(2))}</ValorProdutos></Totais>\n`;
    if(type==='CTe')body+=`  <Tomador><RazaoSocial>${e(doc.recipient||'')}</RazaoSocial><Documento>${e(doc.recipientDoc||'')}</Documento></Tomador>\n  <Prestacao><Origem>${e(doc.origin||'')}</Origem><Destino>${e(doc.destination||'')}</Destino><Natureza>${e(doc.nature||'')}</Natureza><Peso>${e(doc.weight||0)}</Peso><ValorFrete>${e(Number(doc.freight||0).toFixed(2))}</ValorFrete></Prestacao>\n  <DocumentosVinculados>${e(doc.relatedNfeId||'')}</DocumentosVinculados>\n`;
    if(type==='MDFe')body+=`  <ModalRodoviario><Veiculo>${e(doc.vehicle||'')}</Veiculo><Motorista>${e(doc.driver||'')}</Motorista><Origem>${e(doc.origin||'')}</Origem><Destino>${e(doc.destination||'')}</Destino><Percurso>${e(doc.route||'')}</Percurso></ModalRodoviario>\n  <DocumentosVinculados><NFe>${e(doc.relatedNfeId||'')}</NFe><CTe>${e(doc.relatedCteId||'')}</CTe></DocumentosVinculados>\n  <Carga><Peso>${e(doc.weight||0)}</Peso><Valor>${e(Number(doc.value||0).toFixed(2))}</Valor></Carga>\n`;
    return `<?xml version="1.0" encoding="UTF-8"?>\n<DocumentoSimulado xmlns="urn:fiscal-generator:estudo" tipo="${type}" modelo="${model}" validadeFiscal="false">\n  <Identificacao><Numero>${e(doc.number)}</Numero><Serie>${e(doc.series)}</Serie><Chave>${e(doc.key||'')}</Chave><Ambiente>SIMULACAO_EDUCACIONAL</Ambiente><Status>${e(doc.status||'SIMULADO')}</Status></Identificacao>\n${body}  <Aviso>DOCUMENTO SIMULADO — SEM VALIDADE FISCAL — NAO TRANSMITIDO A SEFAZ</Aviso>\n</DocumentoSimulado>`;
  }
};
