/* Fiscal Generator 2.0 — minimal UI and generation flow. */
(function(){
  const app=document.getElementById('app');const C=FGCore;const E=C.esc;const M=C.money;
  const demo={nfe:{issuer:'Empresa de Estudo LTDA',cnpj:'12.345.678/0001-95',issuerIE:'ISENTO',recipient:'Cliente de Estudo LTDA',recipientDoc:'98.765.432/0001-98',uf:'RJ'},cte:{issuer:'Transportes de Estudo LTDA',cnpj:'12.345.678/0001-95',issuerIE:'ISENTO',recipient:'Cliente de Estudo LTDA',recipientDoc:'98.765.432/0001-98',origin:'Rio de Janeiro/RJ',destination:'São Paulo/SP',sender:'Empresa de Estudo LTDA',receiver:'Cliente de Estudo LTDA',cargo:5000,freight:450,weight:120,nature:'Carga geral'},mdfe:{issuer:'Transportes de Estudo LTDA',cnpj:'12.345.678/0001-95',issuerIE:'ISENTO',uf:'RJ',vehicle:'ABC1D23',driver:'Motorista de Estudo',origin:'RJ',destination:'SP',route:'RJ → SP',weight:120,value:5000}};
  function layout(type){const x=demo[type];return `<div class="fg2"><div class="fg2-head"><div><small>FISCAL GENERATOR · LABORATÓRIO</small><h1>${C.TYPES[type.toUpperCase()].label}</h1></div><span>SIMULAÇÃO</span></div><div class="fg2-card"><form id="fg2-form">${fields(type,x)}</form>${type==='nfe'?`<div class="fg2-products"><div class="fg2-row"><b>Produtos</b><button type="button" id="fg2-add">+ Adicionar</button></div><div id="fg2-items"></div></div>`:''}<div class="fg2-actions"><button type="button" onclick="FG2App.draft('${type}')">Salvar rascunho</button><button class="primary" type="button" onclick="FG2App.generate('${type}')">Validar e gerar documento</button></div></div><p class="fg2-note">Documento exclusivamente educacional. Não possui validade fiscal e não é transmitido à SEFAZ.</p></div>`}
  function fields(type,x){const common=[['number','Número','000001'],['series','Série','1'],['issuer','Emitente',x.issuer],['cnpj','CNPJ',x.cnpj]];if(type==='nfe')common.push(['issuerIE','IE',x.issuerIE],['recipient','Destinatário',x.recipient],['recipientDoc','CNPJ / CPF',x.recipientDoc],['uf','UF',x.uf]);if(type==='cte')common.push(['issuerIE','IE',x.issuerIE],['recipient','Tomador',x.recipient],['recipientDoc','CNPJ / CPF',x.recipientDoc],['sender','Remetente',x.sender],['receiver','Recebedor',x.receiver],['origin','Origem',x.origin],['destination','Destino',x.destination],['cargo','Valor da carga',x.cargo],['freight','Frete',x.freight],['weight','Peso bruto (kg)',x.weight],['nature','Natureza',x.nature]);if(type==='mdfe')common.push(['issuerIE','IE',x.issuerIE],['uf','UF',x.uf],['vehicle','Placa',x.vehicle],['driver','Motorista',x.driver],['origin','UF carregamento',x.origin],['destination','UF descarregamento',x.destination],['route','Percurso',x.route],['weight','Peso total (kg)',x.weight],['value','Valor total',x.value]);return common.map(([id,l,v])=>`<label>${E(l)}<input name="${id}" value="${E(v)}"></label>`).join('')}
  function add(){const box=document.getElementById('fg2-items');if(!box)return;const n=box.children.length+1;const r=document.createElement('div');r.className='fg2-item';r.innerHTML=`<input data-k="code" value="${String(n).padStart(3,'0')}" placeholder="Código"><input data-k="description" value="Mercadoria para estudo" placeholder="Descrição"><input data-k="ncm" value="0000.00.00" placeholder="NCM"><input data-k="cfop" value="5102" placeholder="CFOP"><input data-k="qty" type="number" value="1" min="0"><input data-k="unitPrice" type="number" value="150" min="0"><button type="button">Remover</button>`;r.querySelector('button').onclick=()=>r.remove();box.appendChild(r)}
  function items(){return [...document.querySelectorAll('.fg2-item')].map(r=>{const o={};r.querySelectorAll('[data-k]').forEach(i=>o[i.dataset.k]=i.value);o.qty=Number(o.qty||0);o.unitPrice=Number(o.unitPrice||0);o.total=o.qty*o.unitPrice;return o})}
  function generate(type){try{const d=Object.fromEntries(new FormData(document.getElementById('fg2-form')).entries());const doc=C.create(type.toUpperCase(),d,type==='nfe'?items():[]);FGRender.render(doc)}catch(e){window.alert(e.message)}}
  function draft(type){localStorage.setItem('fg2-draft-'+type,JSON.stringify(Object.fromEntries(new FormData(document.getElementById('fg2-form')).entries())));window.alert('Rascunho salvo neste dispositivo.')} 
  function view(type){app.innerHTML=layout(type);if(type==='nfe'){document.getElementById('fg2-add').onclick=add;add()}}
  window.FG2App={view,generate,draft};
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;if(['nfe','cte','mdfe'].includes(v))view(v)}));
})();