/* Fiscal Generator 2.0 — independent A4 renderers. */
(function(){
  const E=FGCore.esc,M=FGCore.money;
  function bars(key){return `<div class="fg-barcode">${String(key||'').split('').map((n,i)=>`<i style="width:${1+(+n%3)}px"></i>`).join('')}</div><small>${E(key)}</small>`}
  function page(title,d,content){return `<div class="fg-overlay"><div class="fg-toolbar"><strong>${title}</strong><button onclick="FG2.close()">Fechar</button><button onclick="window.print()">Imprimir / PDF</button></div><article class="fg-a4"><div class="fg-warning">DOCUMENTO SIMULADO · SEM VALIDADE FISCAL · NÃO TRANSMITIDO À SEFAZ</div><header><div><small>FISCAL GENERATOR · AMBIENTE DE ESTUDO</small><h1>${title}</h1><b>Nº ${E(d.number)} · Série ${E(d.series)}</b></div><div class="fg-key"><span>CHAVE DE ACESSO SIMULADA</span><b>${E(d.key)}</b>${bars(d.key)}</div></header>${content}<footer>Documento exclusivamente educacional · Sem validade fiscal</footer></article></div>`}
  function cells(arr){return `<div class="fg-grid">${arr.map(x=>`<div><small>${E(x[0])}</small><strong>${E(x[1])}</strong></div>`).join('')}</div>`}
  function nfe(d){const rows=(d.productLines||[]).map(p=>`<tr><td>${E(p.code)}</td><td>${E(p.description)}</td><td>${E(p.ncm)}</td><td>${E(p.cfop)}</td><td>${p.qty}</td><td>${M(p.unitPrice)}</td><td>${M(p.total)}</td></tr>`).join('');return page('DANFE — NF-e',d,`<h2>Emitente</h2>${cells([['Razão social',d.issuer],['CNPJ',d.cnpj],['IE',d.issuerIE||'ISENTO'],['UF',d.uf||'RJ']])}<h2>Destinatário</h2>${cells([['Razão social',d.recipient],['CNPJ / CPF',d.recipientDoc],['UF',d.uf||'RJ']])}<h2>Produtos e serviços</h2><table><thead><tr><th>Código</th><th>Descrição</th><th>NCM</th><th>CFOP</th><th>Qtd.</th><th>Unit.</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table>${cells([['Total dos produtos',M(d.totalProducts)],['Modelo',d.model],['Status','SIMULADO']])}`)}
  function cte(d){return page('DACTE — CT-e',d,`<h2>Emitente / transportador</h2>${cells([['Razão social',d.issuer],['CNPJ',d.cnpj],['IE',d.issuerIE||'ISENTO']])}<h2>Prestação</h2>${cells([['Tomador',d.recipient],['Remetente',d.sender],['Recebedor',d.receiver],['Origem',d.origin],['Destino',d.destination]])}<h2>Carga e frete</h2>${cells([['Natureza',d.nature],['Peso bruto',`${d.weight} kg`],['Valor da carga',M(d.cargo)],['Frete',M(d.freight)]])}<h2>Documento relacionado</h2>${cells([['NF-e',d.relatedNfeId||'Nenhuma']])}`)}
  function mdfe(d){return page('DAMDFE — MDF-e',d,`<h2>Emitente</h2>${cells([['Razão social',d.issuer],['CNPJ',d.cnpj],['UF',d.uf||'RJ']])}<h2>Transporte</h2>${cells([['Veículo',d.vehicle],['Motorista',d.driver],['Carregamento',d.origin],['Descarregamento',d.destination],['Percurso',d.route]])}<h2>Carga</h2>${cells([['Peso total',`${d.weight} kg`],['Valor total',M(d.value)]])}<h2>Documentos relacionados</h2>${cells([['CT-e',d.relatedCteId||'Nenhum'],['NF-e',d.relatedNfeId||'Nenhuma']])}`)}
  function render(d){const fn=d.type==='NFE'?nfe:d.type==='CTE'?cte:mdfe;document.body.insertAdjacentHTML('beforeend',fn(d))}
  window.FGRender={render};window.FG2={close:()=>document.querySelector('.fg-overlay')?.remove()};
})();